<?php
/**
 * AiproductdataenhancerJobStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\AiProductDataEnhancer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeminiCommerce\AiProductDataEnhancer\Model;
use \GeminiCommerce\AiProductDataEnhancer\ObjectSerializer;

/**
 * AiproductdataenhancerJobStatus Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\AiProductDataEnhancer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AiproductdataenhancerJobStatus
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'JOB_STATUS_UNKNOWN';

    public const PENDING = 'JOB_STATUS_PENDING';

    public const RUNNING = 'JOB_STATUS_RUNNING';

    public const COMPLETED = 'JOB_STATUS_COMPLETED';

    public const FAILED = 'JOB_STATUS_FAILED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::PENDING,
            self::RUNNING,
            self::COMPLETED,
            self::FAILED
        ];
    }
}


