<?php
/**
 * AiproductdataenhancerFillProductDataRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\AiProductDataEnhancer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * aiproductdataenhancer/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeminiCommerce\AiProductDataEnhancer\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AiproductdataenhancerFillProductDataRequestTest Class Doc Comment
 *
 * @category    Class
 * @description AiproductdataenhancerFillProductDataRequest
 * @package     GeminiCommerce\AiProductDataEnhancer
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AiproductdataenhancerFillProductDataRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AiproductdataenhancerFillProductDataRequest"
     */
    public function testAiproductdataenhancerFillProductDataRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "language_code"
     */
    public function testPropertyLanguageCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_information"
     */
    public function testPropertyProductInformation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_data_to_fill"
     */
    public function testPropertyProductDataToFill()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domains_to_include"
     */
    public function testPropertyDomainsToInclude()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domains_to_exclude"
     */
    public function testPropertyDomainsToExclude()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
